# Generated by Django 3.0.6 on 2020-05-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('round_no', models.IntegerField()),
                ('quota', models.CharField(max_length=5)),
                ('pool', models.CharField(max_length=25)),
                ('institute_full', models.CharField(max_length=75)),
                ('institute_short', models.CharField(max_length=25)),
                ('institute_location', models.CharField(max_length=25)),
                ('program_name', models.CharField(max_length=100)),
                ('program_duration', models.CharField(max_length=25)),
                ('degree_full', models.CharField(max_length=100)),
                ('degree_short', models.CharField(max_length=25)),
                ('category', models.CharField(max_length=25)),
                ('opening_rank', models.IntegerField()),
                ('closing_rank', models.IntegerField()),
                ('is_preparatory', models.IntegerField()),
            ],
        ),
    ]
