# Generated by Django 3.0.6 on 2020-10-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(max_length=31),
        ),
        migrations.AlterField(
            model_name='item',
            name='degree_full',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='degree_short',
            field=models.CharField(max_length=31),
        ),
        migrations.AlterField(
            model_name='item',
            name='institute_full',
            field=models.CharField(max_length=127),
        ),
        migrations.AlterField(
            model_name='item',
            name='institute_location',
            field=models.CharField(max_length=31),
        ),
        migrations.AlterField(
            model_name='item',
            name='institute_short',
            field=models.CharField(max_length=31),
        ),
        migrations.AlterField(
            model_name='item',
            name='pool',
            field=models.CharField(max_length=31),
        ),
        migrations.AlterField(
            model_name='item',
            name='program_duration',
            field=models.CharField(max_length=31),
        ),
        migrations.AlterField(
            model_name='item',
            name='program_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='quota',
            field=models.CharField(max_length=7),
        ),
    ]
