# Generated by Django 3.0.6 on 2020-10-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201006_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='institute_type',
            field=models.CharField(default='IIT', max_length=3),
        ),
    ]
