export const programs = [
  'All',
  'Aerospace Engineering',
  'Agricultural and Food Engineering',
  'Agricultural and Food Engineering with M.Tech. in any of the listed specializations',
  'Agricultural and Food Engineering with M.Tech. in any of the listedspecializations',
  'Applied Geology',
  'Applied Geophysics',
  'Applied Mathematics',
  'Architecture',
  'Artificial Intelligence',
  'Bio Engineering',
  'Bio Technology',
  'Biochemical Engineering and Biotechnology',
  'Biochemical Engineering with M.Tech. in Biochemical Engineering and Biotechnology',
  'Biochemical Engineering with M.Tech. in Biochemical Engineering andBiotechnology',
  'Bioengineering with M.Tech in Biomedical Technology',
  'Biological Engineering',
  'Biological Sciences',
  'Biological Sciences and Bioengineering',
  'Biotechnology and Biochemical Engineering',
  'BS in Mathematics',
  'Ceramic Engineering',
  'Chemical Engineering',
  'Chemical Science and Technology',
  'Chemistry',
  'Civil Engineering',
  'Civil Engineering and M. Tech. in Structural Engineering',
  'Civil Engineering and M.Tech in Transportation Engineering',
  'Civil Engineering and M.Tech. in Environmental Engineering',
  'Civil Engineering with any of the listed specialization',
  'Civil Engineering with M.Tech. in Structural Engineering',
  'Computer Science and Engineering',
  'Data Science and Engineering',
  'Earth Sciences',
  'Economics',
  'Electrical and Electronics Engineering',
  'Electrical Engineering',
  'Electrical Engineering - Power and Automation',
  'Electrical Engineering and M.Tech Power Electronics and Drives',
  'Electrical Engineering with M.Tech. in any of the listed specializations',
  'Electrical Engineering with M.Tech. in Communications and Signal Processing',
  'Electrical Engineering with M.Tech. in Microelectronics',
  'Electrical Engineering with M.Tech. in Power Electronics',
  'Electronics and Communication Engineering',
  'Electronics and Electrical Communication Engineering',
  'Electronics and Electrical Communication Engineering with M.Tech. in any of the listed specializations',
  'Electronics and Electrical Communication Engineering with M.Tech. in anyof the listed specializations',
  'Electronics and Electrical Engineering',
  'Electronics and Instrumentation Engineering',
  'Electronics Engineering',
  'Energy Engineering with M.Tech. in Energy Systems Engineering',
  'Engineering Design',
  'Engineering Physics',
  'Engineering Physics and M.Tech. with specialization in Nano Science',
  'Engineering Science',
  'Environmental Engineering',
  'Environmental Science and Engineering',
  'Exploration Geophysics',
  'Geological Technology',
  'Geophysical Technology',
  'Industrial and Systems Engineering',
  'Industrial and Systems Engineering with M.Tech. in Industrial and Systems Engineering and Management',
  'Industrial and Systems Engineering with M.Tech. in Industrial and SystemsEngineering and Management',
  'Industrial Chemistry',
  'Instrumentation Engineering',
  'Manufacturing Science and Engineering',
  'Manufacturing Science and Engineering with M.Tech. in Industrial and Systems Engineering and Management',
  'Manufacturing Science and Engineering with M.Tech. in Industrial andSystems Engineering and Management',
  'Materials Science and Engineering',
  'Materials Science and Metallurgical Engineering',
  'Materials Science and Technology',
  'Mathematics and Computing',
  'Mathematics and Scientific Computing',
  'Mechanical Engineering',
  'Mechanical Engineering and M. Tech. in Mechanical System Design',
  'Mechanical Engineering and M. Tech. in Thermal Science & Engineering',
  'Mechanical Engineering and M.Tech. in Computer Integrated Manufacturing',
  'Mechanical Engineering and M.Tech. in Computer IntegratedManufacturing',
  'Mechanical Engineering with M.Tech. in any of the listed specializations',
  'Mechanical Engineering with M.Tech. in Manufacturing Engineering',
  'Metallurgical and Materials Engineering',
  'Metallurgical and Materials Engineering and M.Tech. in Materials Science and Engineering',
  'Metallurgical Engineering',
  'Metallurgical Engineering & Materials Science',
  'Metallurgical Engineering and Materials Science',
  'Metallurgical Engineering and Materials Science with M.Tech. in Ceramics and Composites',
  'Metallurgical Engineering and Materials Science with M.Tech. in Metallurgical Process Engineering',
  'Mineral Engineering',
  'Mining Engineering',
  'Mining Machinery Engineering',
  'Mining Safety Engineering',
  'Naval Architecture and Ocean Engineering',
  'Ocean Engineering and Naval Architecture',
  'Petroleum Engineering',
  'Pharmaceutical Engineering & Technology',
  'Pharmaceutics',
  'Physics',
  'Polymer Science and Engineering',
  'Production and Industrial Engineering',
  'Quality Engineering Design and Manufacturing',
  'Textile Technology'
]

export const programDropDownOptions = programs.map(function (element) {
  return {
    key: programs.indexOf(element),
    text: element,
    value: element
  }
})
